#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

branch=$(git symbolic-ref --short HEAD)

if [ "$branch" = "main" ]; then
  echo "Running standard-version..."
  npm run release
else
  echo "Skipping release: not on main branch"
fi
